/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as externalIndexRouteImport } from './routes/(external)/index'
import { Route as mainDashboardRouteRouteImport } from './routes/(main)/dashboard/route'
import { Route as mainDashboardIndexRouteImport } from './routes/(main)/dashboard/index'
import { Route as mainDashboardSplatRouteImport } from './routes/(main)/dashboard/$'
import { Route as mainDashboardAuditRouteRouteImport } from './routes/(main)/dashboard/audit/route'
import { Route as mainDashboardConfigRouteRouteImport } from './routes/(main)/dashboard/config/route'
import { Route as mainDashboardDefaultRouteRouteImport } from './routes/(main)/dashboard/default/route'
import { Route as mainDashboardLedgerRouteRouteImport } from './routes/(main)/dashboard/ledger/route'
import { Route as mainDashboardOperationsRouteRouteImport } from './routes/(main)/dashboard/operations/route'
import { Route as mainDashboardOrdersRouteRouteImport } from './routes/(main)/dashboard/orders/route'
import { Route as mainDashboardPaymentsRouteRouteImport } from './routes/(main)/dashboard/payments/route'
import { Route as mainDashboardTrustRouteRouteImport } from './routes/(main)/dashboard/trust/route'
import { Route as mainDashboardUsersRouteRouteImport } from './routes/(main)/dashboard/users/route'
import { Route as mainDashboardVendorsRouteRouteImport } from './routes/(main)/dashboard/vendors/route'
import { Route as mainAuthV1LoginRouteRouteImport } from './routes/(main)/auth/v1/login/route'
import { Route as mainDashboardOrdersOrderIdRouteRouteImport } from './routes/(main)/dashboard/orders/$orderId/route'
import { Route as mainDashboardUsersUserIdRouteRouteImport } from './routes/(main)/dashboard/users/$userId/route'
import { Route as mainDashboardVendorsVendorIdRouteRouteImport } from './routes/(main)/dashboard/vendors/$vendorId/route'

const externalIndexRoute = externalIndexRouteImport.update({
  id: '/(external)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainDashboardRouteRoute = mainDashboardRouteRouteImport.update({
  id: '/(main)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const mainDashboardIndexRoute = mainDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardSplatRoute = mainDashboardSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardAuditRouteRoute = mainDashboardAuditRouteRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardConfigRouteRoute =
  mainDashboardConfigRouteRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardDefaultRouteRoute =
  mainDashboardDefaultRouteRouteImport.update({
    id: '/default',
    path: '/default',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardLedgerRouteRoute =
  mainDashboardLedgerRouteRouteImport.update({
    id: '/ledger',
    path: '/ledger',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardOperationsRouteRoute =
  mainDashboardOperationsRouteRouteImport.update({
    id: '/operations',
    path: '/operations',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardOrdersRouteRoute =
  mainDashboardOrdersRouteRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardPaymentsRouteRoute =
  mainDashboardPaymentsRouteRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardTrustRouteRoute = mainDashboardTrustRouteRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardUsersRouteRoute = mainDashboardUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardVendorsRouteRoute =
  mainDashboardVendorsRouteRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainAuthV1LoginRouteRoute = mainAuthV1LoginRouteRouteImport.update({
  id: '/(main)/auth/v1/login',
  path: '/auth/v1/login',
  getParentRoute: () => rootRouteImport,
} as any)
const mainDashboardOrdersOrderIdRouteRoute =
  mainDashboardOrdersOrderIdRouteRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => mainDashboardOrdersRouteRoute,
  } as any)
const mainDashboardUsersUserIdRouteRoute =
  mainDashboardUsersUserIdRouteRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => mainDashboardUsersRouteRoute,
  } as any)
const mainDashboardVendorsVendorIdRouteRoute =
  mainDashboardVendorsVendorIdRouteRouteImport.update({
    id: '/$vendorId',
    path: '/$vendorId',
    getParentRoute: () => mainDashboardVendorsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof mainDashboardRouteRouteWithChildren
  '/': typeof externalIndexRoute
  '/dashboard/audit': typeof mainDashboardAuditRouteRoute
  '/dashboard/config': typeof mainDashboardConfigRouteRoute
  '/dashboard/default': typeof mainDashboardDefaultRouteRoute
  '/dashboard/ledger': typeof mainDashboardLedgerRouteRoute
  '/dashboard/operations': typeof mainDashboardOperationsRouteRoute
  '/dashboard/orders': typeof mainDashboardOrdersRouteRouteWithChildren
  '/dashboard/payments': typeof mainDashboardPaymentsRouteRoute
  '/dashboard/trust': typeof mainDashboardTrustRouteRoute
  '/dashboard/users': typeof mainDashboardUsersRouteRouteWithChildren
  '/dashboard/vendors': typeof mainDashboardVendorsRouteRouteWithChildren
  '/dashboard/$': typeof mainDashboardSplatRoute
  '/dashboard/': typeof mainDashboardIndexRoute
  '/auth/v1/login': typeof mainAuthV1LoginRouteRoute
  '/dashboard/orders/$orderId': typeof mainDashboardOrdersOrderIdRouteRoute
  '/dashboard/users/$userId': typeof mainDashboardUsersUserIdRouteRoute
  '/dashboard/vendors/$vendorId': typeof mainDashboardVendorsVendorIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof externalIndexRoute
  '/dashboard/audit': typeof mainDashboardAuditRouteRoute
  '/dashboard/config': typeof mainDashboardConfigRouteRoute
  '/dashboard/default': typeof mainDashboardDefaultRouteRoute
  '/dashboard/ledger': typeof mainDashboardLedgerRouteRoute
  '/dashboard/operations': typeof mainDashboardOperationsRouteRoute
  '/dashboard/orders': typeof mainDashboardOrdersRouteRouteWithChildren
  '/dashboard/payments': typeof mainDashboardPaymentsRouteRoute
  '/dashboard/trust': typeof mainDashboardTrustRouteRoute
  '/dashboard/users': typeof mainDashboardUsersRouteRouteWithChildren
  '/dashboard/vendors': typeof mainDashboardVendorsRouteRouteWithChildren
  '/dashboard/$': typeof mainDashboardSplatRoute
  '/dashboard': typeof mainDashboardIndexRoute
  '/auth/v1/login': typeof mainAuthV1LoginRouteRoute
  '/dashboard/orders/$orderId': typeof mainDashboardOrdersOrderIdRouteRoute
  '/dashboard/users/$userId': typeof mainDashboardUsersUserIdRouteRoute
  '/dashboard/vendors/$vendorId': typeof mainDashboardVendorsVendorIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)/dashboard': typeof mainDashboardRouteRouteWithChildren
  '/(external)/': typeof externalIndexRoute
  '/(main)/dashboard/audit': typeof mainDashboardAuditRouteRoute
  '/(main)/dashboard/config': typeof mainDashboardConfigRouteRoute
  '/(main)/dashboard/default': typeof mainDashboardDefaultRouteRoute
  '/(main)/dashboard/ledger': typeof mainDashboardLedgerRouteRoute
  '/(main)/dashboard/operations': typeof mainDashboardOperationsRouteRoute
  '/(main)/dashboard/orders': typeof mainDashboardOrdersRouteRouteWithChildren
  '/(main)/dashboard/payments': typeof mainDashboardPaymentsRouteRoute
  '/(main)/dashboard/trust': typeof mainDashboardTrustRouteRoute
  '/(main)/dashboard/users': typeof mainDashboardUsersRouteRouteWithChildren
  '/(main)/dashboard/vendors': typeof mainDashboardVendorsRouteRouteWithChildren
  '/(main)/dashboard/$': typeof mainDashboardSplatRoute
  '/(main)/dashboard/': typeof mainDashboardIndexRoute
  '/(main)/auth/v1/login': typeof mainAuthV1LoginRouteRoute
  '/(main)/dashboard/orders/$orderId': typeof mainDashboardOrdersOrderIdRouteRoute
  '/(main)/dashboard/users/$userId': typeof mainDashboardUsersUserIdRouteRoute
  '/(main)/dashboard/vendors/$vendorId': typeof mainDashboardVendorsVendorIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/'
    | '/dashboard/audit'
    | '/dashboard/config'
    | '/dashboard/default'
    | '/dashboard/ledger'
    | '/dashboard/operations'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/trust'
    | '/dashboard/users'
    | '/dashboard/vendors'
    | '/dashboard/$'
    | '/dashboard/'
    | '/auth/v1/login'
    | '/dashboard/orders/$orderId'
    | '/dashboard/users/$userId'
    | '/dashboard/vendors/$vendorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/audit'
    | '/dashboard/config'
    | '/dashboard/default'
    | '/dashboard/ledger'
    | '/dashboard/operations'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/trust'
    | '/dashboard/users'
    | '/dashboard/vendors'
    | '/dashboard/$'
    | '/dashboard'
    | '/auth/v1/login'
    | '/dashboard/orders/$orderId'
    | '/dashboard/users/$userId'
    | '/dashboard/vendors/$vendorId'
  id:
    | '__root__'
    | '/(main)/dashboard'
    | '/(external)/'
    | '/(main)/dashboard/audit'
    | '/(main)/dashboard/config'
    | '/(main)/dashboard/default'
    | '/(main)/dashboard/ledger'
    | '/(main)/dashboard/operations'
    | '/(main)/dashboard/orders'
    | '/(main)/dashboard/payments'
    | '/(main)/dashboard/trust'
    | '/(main)/dashboard/users'
    | '/(main)/dashboard/vendors'
    | '/(main)/dashboard/$'
    | '/(main)/dashboard/'
    | '/(main)/auth/v1/login'
    | '/(main)/dashboard/orders/$orderId'
    | '/(main)/dashboard/users/$userId'
    | '/(main)/dashboard/vendors/$vendorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainDashboardRouteRoute: typeof mainDashboardRouteRouteWithChildren
  externalIndexRoute: typeof externalIndexRoute
  mainAuthV1LoginRouteRoute: typeof mainAuthV1LoginRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(external)/': {
      id: '/(external)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof externalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/dashboard': {
      id: '/(main)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof mainDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/dashboard/': {
      id: '/(main)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof mainDashboardIndexRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/$': {
      id: '/(main)/dashboard/$'
      path: '/$'
      fullPath: '/dashboard/$'
      preLoaderRoute: typeof mainDashboardSplatRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/audit': {
      id: '/(main)/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof mainDashboardAuditRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/config': {
      id: '/(main)/dashboard/config'
      path: '/config'
      fullPath: '/dashboard/config'
      preLoaderRoute: typeof mainDashboardConfigRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/default': {
      id: '/(main)/dashboard/default'
      path: '/default'
      fullPath: '/dashboard/default'
      preLoaderRoute: typeof mainDashboardDefaultRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/ledger': {
      id: '/(main)/dashboard/ledger'
      path: '/ledger'
      fullPath: '/dashboard/ledger'
      preLoaderRoute: typeof mainDashboardLedgerRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/operations': {
      id: '/(main)/dashboard/operations'
      path: '/operations'
      fullPath: '/dashboard/operations'
      preLoaderRoute: typeof mainDashboardOperationsRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/orders': {
      id: '/(main)/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof mainDashboardOrdersRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/payments': {
      id: '/(main)/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof mainDashboardPaymentsRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/trust': {
      id: '/(main)/dashboard/trust'
      path: '/trust'
      fullPath: '/dashboard/trust'
      preLoaderRoute: typeof mainDashboardTrustRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/users': {
      id: '/(main)/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof mainDashboardUsersRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/vendors': {
      id: '/(main)/dashboard/vendors'
      path: '/vendors'
      fullPath: '/dashboard/vendors'
      preLoaderRoute: typeof mainDashboardVendorsRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/auth/v1/login': {
      id: '/(main)/auth/v1/login'
      path: '/auth/v1/login'
      fullPath: '/auth/v1/login'
      preLoaderRoute: typeof mainAuthV1LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/dashboard/orders/$orderId': {
      id: '/(main)/dashboard/orders/$orderId'
      path: '/$orderId'
      fullPath: '/dashboard/orders/$orderId'
      preLoaderRoute: typeof mainDashboardOrdersOrderIdRouteRouteImport
      parentRoute: typeof mainDashboardOrdersRouteRoute
    }
    '/(main)/dashboard/users/$userId': {
      id: '/(main)/dashboard/users/$userId'
      path: '/$userId'
      fullPath: '/dashboard/users/$userId'
      preLoaderRoute: typeof mainDashboardUsersUserIdRouteRouteImport
      parentRoute: typeof mainDashboardUsersRouteRoute
    }
    '/(main)/dashboard/vendors/$vendorId': {
      id: '/(main)/dashboard/vendors/$vendorId'
      path: '/$vendorId'
      fullPath: '/dashboard/vendors/$vendorId'
      preLoaderRoute: typeof mainDashboardVendorsVendorIdRouteRouteImport
      parentRoute: typeof mainDashboardVendorsRouteRoute
    }
  }
}

interface mainDashboardOrdersRouteRouteChildren {
  mainDashboardOrdersOrderIdRouteRoute: typeof mainDashboardOrdersOrderIdRouteRoute
}

const mainDashboardOrdersRouteRouteChildren: mainDashboardOrdersRouteRouteChildren =
  {
    mainDashboardOrdersOrderIdRouteRoute: mainDashboardOrdersOrderIdRouteRoute,
  }

const mainDashboardOrdersRouteRouteWithChildren =
  mainDashboardOrdersRouteRoute._addFileChildren(
    mainDashboardOrdersRouteRouteChildren,
  )

interface mainDashboardUsersRouteRouteChildren {
  mainDashboardUsersUserIdRouteRoute: typeof mainDashboardUsersUserIdRouteRoute
}

const mainDashboardUsersRouteRouteChildren: mainDashboardUsersRouteRouteChildren =
  {
    mainDashboardUsersUserIdRouteRoute: mainDashboardUsersUserIdRouteRoute,
  }

const mainDashboardUsersRouteRouteWithChildren =
  mainDashboardUsersRouteRoute._addFileChildren(
    mainDashboardUsersRouteRouteChildren,
  )

interface mainDashboardVendorsRouteRouteChildren {
  mainDashboardVendorsVendorIdRouteRoute: typeof mainDashboardVendorsVendorIdRouteRoute
}

const mainDashboardVendorsRouteRouteChildren: mainDashboardVendorsRouteRouteChildren =
  {
    mainDashboardVendorsVendorIdRouteRoute:
      mainDashboardVendorsVendorIdRouteRoute,
  }

const mainDashboardVendorsRouteRouteWithChildren =
  mainDashboardVendorsRouteRoute._addFileChildren(
    mainDashboardVendorsRouteRouteChildren,
  )

interface mainDashboardRouteRouteChildren {
  mainDashboardAuditRouteRoute: typeof mainDashboardAuditRouteRoute
  mainDashboardConfigRouteRoute: typeof mainDashboardConfigRouteRoute
  mainDashboardDefaultRouteRoute: typeof mainDashboardDefaultRouteRoute
  mainDashboardLedgerRouteRoute: typeof mainDashboardLedgerRouteRoute
  mainDashboardOperationsRouteRoute: typeof mainDashboardOperationsRouteRoute
  mainDashboardOrdersRouteRoute: typeof mainDashboardOrdersRouteRouteWithChildren
  mainDashboardPaymentsRouteRoute: typeof mainDashboardPaymentsRouteRoute
  mainDashboardTrustRouteRoute: typeof mainDashboardTrustRouteRoute
  mainDashboardUsersRouteRoute: typeof mainDashboardUsersRouteRouteWithChildren
  mainDashboardVendorsRouteRoute: typeof mainDashboardVendorsRouteRouteWithChildren
  mainDashboardSplatRoute: typeof mainDashboardSplatRoute
  mainDashboardIndexRoute: typeof mainDashboardIndexRoute
}

const mainDashboardRouteRouteChildren: mainDashboardRouteRouteChildren = {
  mainDashboardAuditRouteRoute: mainDashboardAuditRouteRoute,
  mainDashboardConfigRouteRoute: mainDashboardConfigRouteRoute,
  mainDashboardDefaultRouteRoute: mainDashboardDefaultRouteRoute,
  mainDashboardLedgerRouteRoute: mainDashboardLedgerRouteRoute,
  mainDashboardOperationsRouteRoute: mainDashboardOperationsRouteRoute,
  mainDashboardOrdersRouteRoute: mainDashboardOrdersRouteRouteWithChildren,
  mainDashboardPaymentsRouteRoute: mainDashboardPaymentsRouteRoute,
  mainDashboardTrustRouteRoute: mainDashboardTrustRouteRoute,
  mainDashboardUsersRouteRoute: mainDashboardUsersRouteRouteWithChildren,
  mainDashboardVendorsRouteRoute: mainDashboardVendorsRouteRouteWithChildren,
  mainDashboardSplatRoute: mainDashboardSplatRoute,
  mainDashboardIndexRoute: mainDashboardIndexRoute,
}

const mainDashboardRouteRouteWithChildren =
  mainDashboardRouteRoute._addFileChildren(mainDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  mainDashboardRouteRoute: mainDashboardRouteRouteWithChildren,
  externalIndexRoute: externalIndexRoute,
  mainAuthV1LoginRouteRoute: mainAuthV1LoginRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
