// Vendor auth strings (Hindi-first, English fallback) — access-code-only
// (028). Vendor accounts are admin-created: no guest browse, no signup link.

const Map<String, String> vendorStringsHi = {
  'appName': 'Shodasha Vendor',
  'appTagline': 'Delivery partner app',
  'loginTitle': 'Access code se login karein',
  'loginSubtitle': 'Admin se apna access code lein',
  'phoneLabel': 'Mobile number',
  'phoneHint': '93021 90067',
  'phoneError': 'Sahi 10-digit mobile number likhein (6–9 se shuru)',
  'codeLabel': 'Access code',
  'codeHint': 'Admin se mila code likhein',
  'codeError': 'Sahi access code likhein (kam se kam 4 akshar)',
  'loginGo': 'Login karein',
  'loggingIn': 'Login ho raha hai…',
  'invalidCredentials': 'Galat phone ya code — dobara try karein',
  'rateLimited': 'Bahut koshish ho gayi — thodi der ruk kar try karein',
  'deviceLimit': 'Is device par bahut se login — support se sampark karein',
  'serverError': 'Server me dikkat — thodi der me retry karein',
  'networkError': 'Network me dikkat — dobara try karein',
  'newDevice': 'Naya device detect hua — purana session surakshit hai',
  'notVendor': 'Ye number vendor account se juda nahi — admin se sampark karein',
  'demoLogin': 'Demo try karein (bina code)',
  'demoTitle': 'Demo login',
  'demoHint': 'Seeded demo account — QA ke liye, bina access code',
  'demoVendor': 'Demo vendor bharein',
  'demoGo': 'Demo se login karein',
  'sessionExpired': 'Session khatam ho gaya — dobara login karein',
  'capExpiring': 'Login kal khatam hoga — kaam ke baad dobara login karein',
};
