/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as externalIndexRouteImport } from './routes/(external)/index'
import { Route as mainDashboardRouteRouteImport } from './routes/(main)/dashboard/route'
import { Route as mainDashboardIndexRouteImport } from './routes/(main)/dashboard/index'
import { Route as mainDashboardSplatRouteImport } from './routes/(main)/dashboard/$'
import { Route as mainDashboardAuditRouteRouteImport } from './routes/(main)/dashboard/audit/route'
import { Route as mainDashboardConfigRouteRouteImport } from './routes/(main)/dashboard/config/route'
import { Route as mainDashboardDefaultRouteRouteImport } from './routes/(main)/dashboard/default/route'
import { Route as mainDashboardLedgerRouteRouteImport } from './routes/(main)/dashboard/ledger/route'
import { Route as mainDashboardOrdersRouteRouteImport } from './routes/(main)/dashboard/orders/route'
import { Route as mainDashboardPaymentsRouteRouteImport } from './routes/(main)/dashboard/payments/route'
import { Route as mainDashboardTrustRouteRouteImport } from './routes/(main)/dashboard/trust/route'
import { Route as mainDashboardUsersRouteRouteImport } from './routes/(main)/dashboard/users/route'
import { Route as mainDashboardVendorsRouteRouteImport } from './routes/(main)/dashboard/vendors/route'
import { Route as mainVendorguardRouteRouteImport } from './routes/(main)/vendor/(guard)/route'
import { Route as mainAuthV1LoginRouteRouteImport } from './routes/(main)/auth/v1/login/route'
import { Route as mainDashboardAnalyticsIndexRouteImport } from './routes/(main)/dashboard/analytics/index'
import { Route as mainDashboardDispatchIndexRouteImport } from './routes/(main)/dashboard/dispatch/index'
import { Route as mainDashboardFinanceIndexRouteImport } from './routes/(main)/dashboard/finance/index'
import { Route as mainDashboardOrdersIndexRouteImport } from './routes/(main)/dashboard/orders/index'
import { Route as mainDashboardOrdersOrderIdRouteRouteImport } from './routes/(main)/dashboard/orders/$orderId/route'
import { Route as mainDashboardUsersIndexRouteImport } from './routes/(main)/dashboard/users/index'
import { Route as mainDashboardUsersUserIdRouteRouteImport } from './routes/(main)/dashboard/users/$userId/route'
import { Route as mainDashboardVendorsIndexRouteImport } from './routes/(main)/dashboard/vendors/index'
import { Route as mainDashboardVendorsVendorIdRouteRouteImport } from './routes/(main)/dashboard/vendors/$vendorId/route'
import { Route as mainVendorguardIndexRouteImport } from './routes/(main)/vendor/(guard)/index'
import { Route as mainVendorLoginIndexRouteImport } from './routes/(main)/vendor/login/index'
import { Route as mainDashboardVendorsVendorIdIndexRouteImport } from './routes/(main)/dashboard/vendors/$vendorId/index'
import { Route as mainVendorguardCollectionsIndexRouteImport } from './routes/(main)/vendor/(guard)/collections/index'
import { Route as mainVendorguardDepositsIndexRouteImport } from './routes/(main)/vendor/(guard)/deposits/index'
import { Route as mainVendorguardPayoutsIndexRouteImport } from './routes/(main)/vendor/(guard)/payouts/index'
import { Route as mainVendorguardProfileIndexRouteImport } from './routes/(main)/vendor/(guard)/profile/index'
import { Route as mainVendorguardRouteIndexRouteImport } from './routes/(main)/vendor/(guard)/route/index'
import { Route as mainVendorguardSupportIndexRouteImport } from './routes/(main)/vendor/(guard)/support/index'
import { Route as mainDashboardVendorsVendorIdAccessIndexRouteImport } from './routes/(main)/dashboard/vendors/$vendorId/access/index'
import { Route as mainDashboardVendorsVendorIdPreviewIndexRouteImport } from './routes/(main)/dashboard/vendors/$vendorId/preview/index'
import { Route as mainVendorguardStopsStopIdIndexRouteImport } from './routes/(main)/vendor/(guard)/stops/$stopId/index'

const externalIndexRoute = externalIndexRouteImport.update({
  id: '/(external)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainDashboardRouteRoute = mainDashboardRouteRouteImport.update({
  id: '/(main)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const mainDashboardIndexRoute = mainDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardSplatRoute = mainDashboardSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardAuditRouteRoute = mainDashboardAuditRouteRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardConfigRouteRoute =
  mainDashboardConfigRouteRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardDefaultRouteRoute =
  mainDashboardDefaultRouteRouteImport.update({
    id: '/default',
    path: '/default',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardLedgerRouteRoute =
  mainDashboardLedgerRouteRouteImport.update({
    id: '/ledger',
    path: '/ledger',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardOrdersRouteRoute =
  mainDashboardOrdersRouteRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardPaymentsRouteRoute =
  mainDashboardPaymentsRouteRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardTrustRouteRoute = mainDashboardTrustRouteRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardUsersRouteRoute = mainDashboardUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardVendorsRouteRoute =
  mainDashboardVendorsRouteRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainVendorguardRouteRoute = mainVendorguardRouteRouteImport.update({
  id: '/(main)/vendor/(guard)',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const mainAuthV1LoginRouteRoute = mainAuthV1LoginRouteRouteImport.update({
  id: '/(main)/auth/v1/login',
  path: '/auth/v1/login',
  getParentRoute: () => rootRouteImport,
} as any)
const mainDashboardAnalyticsIndexRoute =
  mainDashboardAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardDispatchIndexRoute =
  mainDashboardDispatchIndexRouteImport.update({
    id: '/dispatch/',
    path: '/dispatch/',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardFinanceIndexRoute =
  mainDashboardFinanceIndexRouteImport.update({
    id: '/finance/',
    path: '/finance/',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardOrdersIndexRoute =
  mainDashboardOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => mainDashboardOrdersRouteRoute,
  } as any)
const mainDashboardOrdersOrderIdRouteRoute =
  mainDashboardOrdersOrderIdRouteRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => mainDashboardOrdersRouteRoute,
  } as any)
const mainDashboardUsersIndexRoute = mainDashboardUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainDashboardUsersRouteRoute,
} as any)
const mainDashboardUsersUserIdRouteRoute =
  mainDashboardUsersUserIdRouteRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => mainDashboardUsersRouteRoute,
  } as any)
const mainDashboardVendorsIndexRoute =
  mainDashboardVendorsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => mainDashboardVendorsRouteRoute,
  } as any)
const mainDashboardVendorsVendorIdRouteRoute =
  mainDashboardVendorsVendorIdRouteRouteImport.update({
    id: '/$vendorId',
    path: '/$vendorId',
    getParentRoute: () => mainDashboardVendorsRouteRoute,
  } as any)
const mainVendorguardIndexRoute = mainVendorguardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainVendorguardRouteRoute,
} as any)
const mainVendorLoginIndexRoute = mainVendorLoginIndexRouteImport.update({
  id: '/(main)/vendor/login/',
  path: '/vendor/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainDashboardVendorsVendorIdIndexRoute =
  mainDashboardVendorsVendorIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => mainDashboardVendorsVendorIdRouteRoute,
  } as any)
const mainVendorguardCollectionsIndexRoute =
  mainVendorguardCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => mainVendorguardRouteRoute,
  } as any)
const mainVendorguardDepositsIndexRoute =
  mainVendorguardDepositsIndexRouteImport.update({
    id: '/deposits/',
    path: '/deposits/',
    getParentRoute: () => mainVendorguardRouteRoute,
  } as any)
const mainVendorguardPayoutsIndexRoute =
  mainVendorguardPayoutsIndexRouteImport.update({
    id: '/payouts/',
    path: '/payouts/',
    getParentRoute: () => mainVendorguardRouteRoute,
  } as any)
const mainVendorguardProfileIndexRoute =
  mainVendorguardProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => mainVendorguardRouteRoute,
  } as any)
const mainVendorguardRouteIndexRoute =
  mainVendorguardRouteIndexRouteImport.update({
    id: '/route/',
    path: '/route/',
    getParentRoute: () => mainVendorguardRouteRoute,
  } as any)
const mainVendorguardSupportIndexRoute =
  mainVendorguardSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => mainVendorguardRouteRoute,
  } as any)
const mainDashboardVendorsVendorIdAccessIndexRoute =
  mainDashboardVendorsVendorIdAccessIndexRouteImport.update({
    id: '/access/',
    path: '/access/',
    getParentRoute: () => mainDashboardVendorsVendorIdRouteRoute,
  } as any)
const mainDashboardVendorsVendorIdPreviewIndexRoute =
  mainDashboardVendorsVendorIdPreviewIndexRouteImport.update({
    id: '/preview/',
    path: '/preview/',
    getParentRoute: () => mainDashboardVendorsVendorIdRouteRoute,
  } as any)
const mainVendorguardStopsStopIdIndexRoute =
  mainVendorguardStopsStopIdIndexRouteImport.update({
    id: '/stops/$stopId/',
    path: '/stops/$stopId/',
    getParentRoute: () => mainVendorguardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof mainDashboardRouteRouteWithChildren
  '/': typeof externalIndexRoute
  '/dashboard/audit': typeof mainDashboardAuditRouteRoute
  '/dashboard/config': typeof mainDashboardConfigRouteRoute
  '/dashboard/default': typeof mainDashboardDefaultRouteRoute
  '/dashboard/ledger': typeof mainDashboardLedgerRouteRoute
  '/dashboard/orders': typeof mainDashboardOrdersRouteRouteWithChildren
  '/dashboard/payments': typeof mainDashboardPaymentsRouteRoute
  '/dashboard/trust': typeof mainDashboardTrustRouteRoute
  '/dashboard/users': typeof mainDashboardUsersRouteRouteWithChildren
  '/dashboard/vendors': typeof mainDashboardVendorsRouteRouteWithChildren
  '/vendor': typeof mainVendorguardRouteRouteWithChildren
  '/dashboard/$': typeof mainDashboardSplatRoute
  '/dashboard/': typeof mainDashboardIndexRoute
  '/auth/v1/login': typeof mainAuthV1LoginRouteRoute
  '/dashboard/orders/$orderId': typeof mainDashboardOrdersOrderIdRouteRoute
  '/dashboard/users/$userId': typeof mainDashboardUsersUserIdRouteRoute
  '/dashboard/vendors/$vendorId': typeof mainDashboardVendorsVendorIdRouteRouteWithChildren
  '/dashboard/analytics/': typeof mainDashboardAnalyticsIndexRoute
  '/dashboard/dispatch/': typeof mainDashboardDispatchIndexRoute
  '/dashboard/finance/': typeof mainDashboardFinanceIndexRoute
  '/dashboard/orders/': typeof mainDashboardOrdersIndexRoute
  '/dashboard/users/': typeof mainDashboardUsersIndexRoute
  '/dashboard/vendors/': typeof mainDashboardVendorsIndexRoute
  '/vendor/': typeof mainVendorguardIndexRoute
  '/vendor/login/': typeof mainVendorLoginIndexRoute
  '/dashboard/vendors/$vendorId/': typeof mainDashboardVendorsVendorIdIndexRoute
  '/vendor/collections/': typeof mainVendorguardCollectionsIndexRoute
  '/vendor/deposits/': typeof mainVendorguardDepositsIndexRoute
  '/vendor/payouts/': typeof mainVendorguardPayoutsIndexRoute
  '/vendor/profile/': typeof mainVendorguardProfileIndexRoute
  '/vendor/route/': typeof mainVendorguardRouteIndexRoute
  '/vendor/support/': typeof mainVendorguardSupportIndexRoute
  '/dashboard/vendors/$vendorId/access/': typeof mainDashboardVendorsVendorIdAccessIndexRoute
  '/dashboard/vendors/$vendorId/preview/': typeof mainDashboardVendorsVendorIdPreviewIndexRoute
  '/vendor/stops/$stopId/': typeof mainVendorguardStopsStopIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof externalIndexRoute
  '/dashboard/audit': typeof mainDashboardAuditRouteRoute
  '/dashboard/config': typeof mainDashboardConfigRouteRoute
  '/dashboard/default': typeof mainDashboardDefaultRouteRoute
  '/dashboard/ledger': typeof mainDashboardLedgerRouteRoute
  '/dashboard/payments': typeof mainDashboardPaymentsRouteRoute
  '/dashboard/trust': typeof mainDashboardTrustRouteRoute
  '/dashboard/$': typeof mainDashboardSplatRoute
  '/dashboard': typeof mainDashboardIndexRoute
  '/auth/v1/login': typeof mainAuthV1LoginRouteRoute
  '/dashboard/orders/$orderId': typeof mainDashboardOrdersOrderIdRouteRoute
  '/dashboard/users/$userId': typeof mainDashboardUsersUserIdRouteRoute
  '/dashboard/analytics': typeof mainDashboardAnalyticsIndexRoute
  '/dashboard/dispatch': typeof mainDashboardDispatchIndexRoute
  '/dashboard/finance': typeof mainDashboardFinanceIndexRoute
  '/dashboard/orders': typeof mainDashboardOrdersIndexRoute
  '/dashboard/users': typeof mainDashboardUsersIndexRoute
  '/dashboard/vendors': typeof mainDashboardVendorsIndexRoute
  '/vendor': typeof mainVendorguardIndexRoute
  '/vendor/login': typeof mainVendorLoginIndexRoute
  '/dashboard/vendors/$vendorId': typeof mainDashboardVendorsVendorIdIndexRoute
  '/vendor/collections': typeof mainVendorguardCollectionsIndexRoute
  '/vendor/deposits': typeof mainVendorguardDepositsIndexRoute
  '/vendor/payouts': typeof mainVendorguardPayoutsIndexRoute
  '/vendor/profile': typeof mainVendorguardProfileIndexRoute
  '/vendor/route': typeof mainVendorguardRouteIndexRoute
  '/vendor/support': typeof mainVendorguardSupportIndexRoute
  '/dashboard/vendors/$vendorId/access': typeof mainDashboardVendorsVendorIdAccessIndexRoute
  '/dashboard/vendors/$vendorId/preview': typeof mainDashboardVendorsVendorIdPreviewIndexRoute
  '/vendor/stops/$stopId': typeof mainVendorguardStopsStopIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)/dashboard': typeof mainDashboardRouteRouteWithChildren
  '/(external)/': typeof externalIndexRoute
  '/(main)/dashboard/audit': typeof mainDashboardAuditRouteRoute
  '/(main)/dashboard/config': typeof mainDashboardConfigRouteRoute
  '/(main)/dashboard/default': typeof mainDashboardDefaultRouteRoute
  '/(main)/dashboard/ledger': typeof mainDashboardLedgerRouteRoute
  '/(main)/dashboard/orders': typeof mainDashboardOrdersRouteRouteWithChildren
  '/(main)/dashboard/payments': typeof mainDashboardPaymentsRouteRoute
  '/(main)/dashboard/trust': typeof mainDashboardTrustRouteRoute
  '/(main)/dashboard/users': typeof mainDashboardUsersRouteRouteWithChildren
  '/(main)/dashboard/vendors': typeof mainDashboardVendorsRouteRouteWithChildren
  '/(main)/vendor/(guard)': typeof mainVendorguardRouteRouteWithChildren
  '/(main)/dashboard/$': typeof mainDashboardSplatRoute
  '/(main)/dashboard/': typeof mainDashboardIndexRoute
  '/(main)/auth/v1/login': typeof mainAuthV1LoginRouteRoute
  '/(main)/dashboard/orders/$orderId': typeof mainDashboardOrdersOrderIdRouteRoute
  '/(main)/dashboard/users/$userId': typeof mainDashboardUsersUserIdRouteRoute
  '/(main)/dashboard/vendors/$vendorId': typeof mainDashboardVendorsVendorIdRouteRouteWithChildren
  '/(main)/dashboard/analytics/': typeof mainDashboardAnalyticsIndexRoute
  '/(main)/dashboard/dispatch/': typeof mainDashboardDispatchIndexRoute
  '/(main)/dashboard/finance/': typeof mainDashboardFinanceIndexRoute
  '/(main)/dashboard/orders/': typeof mainDashboardOrdersIndexRoute
  '/(main)/dashboard/users/': typeof mainDashboardUsersIndexRoute
  '/(main)/dashboard/vendors/': typeof mainDashboardVendorsIndexRoute
  '/(main)/vendor/(guard)/': typeof mainVendorguardIndexRoute
  '/(main)/vendor/login/': typeof mainVendorLoginIndexRoute
  '/(main)/dashboard/vendors/$vendorId/': typeof mainDashboardVendorsVendorIdIndexRoute
  '/(main)/vendor/(guard)/collections/': typeof mainVendorguardCollectionsIndexRoute
  '/(main)/vendor/(guard)/deposits/': typeof mainVendorguardDepositsIndexRoute
  '/(main)/vendor/(guard)/payouts/': typeof mainVendorguardPayoutsIndexRoute
  '/(main)/vendor/(guard)/profile/': typeof mainVendorguardProfileIndexRoute
  '/(main)/vendor/(guard)/route/': typeof mainVendorguardRouteIndexRoute
  '/(main)/vendor/(guard)/support/': typeof mainVendorguardSupportIndexRoute
  '/(main)/dashboard/vendors/$vendorId/access/': typeof mainDashboardVendorsVendorIdAccessIndexRoute
  '/(main)/dashboard/vendors/$vendorId/preview/': typeof mainDashboardVendorsVendorIdPreviewIndexRoute
  '/(main)/vendor/(guard)/stops/$stopId/': typeof mainVendorguardStopsStopIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/'
    | '/dashboard/audit'
    | '/dashboard/config'
    | '/dashboard/default'
    | '/dashboard/ledger'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/trust'
    | '/dashboard/users'
    | '/dashboard/vendors'
    | '/vendor'
    | '/dashboard/$'
    | '/dashboard/'
    | '/auth/v1/login'
    | '/dashboard/orders/$orderId'
    | '/dashboard/users/$userId'
    | '/dashboard/vendors/$vendorId'
    | '/dashboard/analytics/'
    | '/dashboard/dispatch/'
    | '/dashboard/finance/'
    | '/dashboard/orders/'
    | '/dashboard/users/'
    | '/dashboard/vendors/'
    | '/vendor/'
    | '/vendor/login/'
    | '/dashboard/vendors/$vendorId/'
    | '/vendor/collections/'
    | '/vendor/deposits/'
    | '/vendor/payouts/'
    | '/vendor/profile/'
    | '/vendor/route/'
    | '/vendor/support/'
    | '/dashboard/vendors/$vendorId/access/'
    | '/dashboard/vendors/$vendorId/preview/'
    | '/vendor/stops/$stopId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/audit'
    | '/dashboard/config'
    | '/dashboard/default'
    | '/dashboard/ledger'
    | '/dashboard/payments'
    | '/dashboard/trust'
    | '/dashboard/$'
    | '/dashboard'
    | '/auth/v1/login'
    | '/dashboard/orders/$orderId'
    | '/dashboard/users/$userId'
    | '/dashboard/analytics'
    | '/dashboard/dispatch'
    | '/dashboard/finance'
    | '/dashboard/orders'
    | '/dashboard/users'
    | '/dashboard/vendors'
    | '/vendor'
    | '/vendor/login'
    | '/dashboard/vendors/$vendorId'
    | '/vendor/collections'
    | '/vendor/deposits'
    | '/vendor/payouts'
    | '/vendor/profile'
    | '/vendor/route'
    | '/vendor/support'
    | '/dashboard/vendors/$vendorId/access'
    | '/dashboard/vendors/$vendorId/preview'
    | '/vendor/stops/$stopId'
  id:
    | '__root__'
    | '/(main)/dashboard'
    | '/(external)/'
    | '/(main)/dashboard/audit'
    | '/(main)/dashboard/config'
    | '/(main)/dashboard/default'
    | '/(main)/dashboard/ledger'
    | '/(main)/dashboard/orders'
    | '/(main)/dashboard/payments'
    | '/(main)/dashboard/trust'
    | '/(main)/dashboard/users'
    | '/(main)/dashboard/vendors'
    | '/(main)/vendor/(guard)'
    | '/(main)/dashboard/$'
    | '/(main)/dashboard/'
    | '/(main)/auth/v1/login'
    | '/(main)/dashboard/orders/$orderId'
    | '/(main)/dashboard/users/$userId'
    | '/(main)/dashboard/vendors/$vendorId'
    | '/(main)/dashboard/analytics/'
    | '/(main)/dashboard/dispatch/'
    | '/(main)/dashboard/finance/'
    | '/(main)/dashboard/orders/'
    | '/(main)/dashboard/users/'
    | '/(main)/dashboard/vendors/'
    | '/(main)/vendor/(guard)/'
    | '/(main)/vendor/login/'
    | '/(main)/dashboard/vendors/$vendorId/'
    | '/(main)/vendor/(guard)/collections/'
    | '/(main)/vendor/(guard)/deposits/'
    | '/(main)/vendor/(guard)/payouts/'
    | '/(main)/vendor/(guard)/profile/'
    | '/(main)/vendor/(guard)/route/'
    | '/(main)/vendor/(guard)/support/'
    | '/(main)/dashboard/vendors/$vendorId/access/'
    | '/(main)/dashboard/vendors/$vendorId/preview/'
    | '/(main)/vendor/(guard)/stops/$stopId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainDashboardRouteRoute: typeof mainDashboardRouteRouteWithChildren
  externalIndexRoute: typeof externalIndexRoute
  mainVendorguardRouteRoute: typeof mainVendorguardRouteRouteWithChildren
  mainAuthV1LoginRouteRoute: typeof mainAuthV1LoginRouteRoute
  mainVendorLoginIndexRoute: typeof mainVendorLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(external)/': {
      id: '/(external)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof externalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/dashboard': {
      id: '/(main)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof mainDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/dashboard/': {
      id: '/(main)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof mainDashboardIndexRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/$': {
      id: '/(main)/dashboard/$'
      path: '/$'
      fullPath: '/dashboard/$'
      preLoaderRoute: typeof mainDashboardSplatRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/audit': {
      id: '/(main)/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof mainDashboardAuditRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/config': {
      id: '/(main)/dashboard/config'
      path: '/config'
      fullPath: '/dashboard/config'
      preLoaderRoute: typeof mainDashboardConfigRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/default': {
      id: '/(main)/dashboard/default'
      path: '/default'
      fullPath: '/dashboard/default'
      preLoaderRoute: typeof mainDashboardDefaultRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/ledger': {
      id: '/(main)/dashboard/ledger'
      path: '/ledger'
      fullPath: '/dashboard/ledger'
      preLoaderRoute: typeof mainDashboardLedgerRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/orders': {
      id: '/(main)/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof mainDashboardOrdersRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/payments': {
      id: '/(main)/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof mainDashboardPaymentsRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/trust': {
      id: '/(main)/dashboard/trust'
      path: '/trust'
      fullPath: '/dashboard/trust'
      preLoaderRoute: typeof mainDashboardTrustRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/users': {
      id: '/(main)/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof mainDashboardUsersRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/vendors': {
      id: '/(main)/dashboard/vendors'
      path: '/vendors'
      fullPath: '/dashboard/vendors'
      preLoaderRoute: typeof mainDashboardVendorsRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/vendor/(guard)': {
      id: '/(main)/vendor/(guard)'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof mainVendorguardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/auth/v1/login': {
      id: '/(main)/auth/v1/login'
      path: '/auth/v1/login'
      fullPath: '/auth/v1/login'
      preLoaderRoute: typeof mainAuthV1LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/dashboard/analytics/': {
      id: '/(main)/dashboard/analytics/'
      path: '/analytics'
      fullPath: '/dashboard/analytics/'
      preLoaderRoute: typeof mainDashboardAnalyticsIndexRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/dispatch/': {
      id: '/(main)/dashboard/dispatch/'
      path: '/dispatch'
      fullPath: '/dashboard/dispatch/'
      preLoaderRoute: typeof mainDashboardDispatchIndexRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/finance/': {
      id: '/(main)/dashboard/finance/'
      path: '/finance'
      fullPath: '/dashboard/finance/'
      preLoaderRoute: typeof mainDashboardFinanceIndexRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/orders/': {
      id: '/(main)/dashboard/orders/'
      path: '/'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof mainDashboardOrdersIndexRouteImport
      parentRoute: typeof mainDashboardOrdersRouteRoute
    }
    '/(main)/dashboard/orders/$orderId': {
      id: '/(main)/dashboard/orders/$orderId'
      path: '/$orderId'
      fullPath: '/dashboard/orders/$orderId'
      preLoaderRoute: typeof mainDashboardOrdersOrderIdRouteRouteImport
      parentRoute: typeof mainDashboardOrdersRouteRoute
    }
    '/(main)/dashboard/users/': {
      id: '/(main)/dashboard/users/'
      path: '/'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof mainDashboardUsersIndexRouteImport
      parentRoute: typeof mainDashboardUsersRouteRoute
    }
    '/(main)/dashboard/users/$userId': {
      id: '/(main)/dashboard/users/$userId'
      path: '/$userId'
      fullPath: '/dashboard/users/$userId'
      preLoaderRoute: typeof mainDashboardUsersUserIdRouteRouteImport
      parentRoute: typeof mainDashboardUsersRouteRoute
    }
    '/(main)/dashboard/vendors/': {
      id: '/(main)/dashboard/vendors/'
      path: '/'
      fullPath: '/dashboard/vendors/'
      preLoaderRoute: typeof mainDashboardVendorsIndexRouteImport
      parentRoute: typeof mainDashboardVendorsRouteRoute
    }
    '/(main)/dashboard/vendors/$vendorId': {
      id: '/(main)/dashboard/vendors/$vendorId'
      path: '/$vendorId'
      fullPath: '/dashboard/vendors/$vendorId'
      preLoaderRoute: typeof mainDashboardVendorsVendorIdRouteRouteImport
      parentRoute: typeof mainDashboardVendorsRouteRoute
    }
    '/(main)/vendor/(guard)/': {
      id: '/(main)/vendor/(guard)/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof mainVendorguardIndexRouteImport
      parentRoute: typeof mainVendorguardRouteRoute
    }
    '/(main)/vendor/login/': {
      id: '/(main)/vendor/login/'
      path: '/vendor/login'
      fullPath: '/vendor/login/'
      preLoaderRoute: typeof mainVendorLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/dashboard/vendors/$vendorId/': {
      id: '/(main)/dashboard/vendors/$vendorId/'
      path: '/'
      fullPath: '/dashboard/vendors/$vendorId/'
      preLoaderRoute: typeof mainDashboardVendorsVendorIdIndexRouteImport
      parentRoute: typeof mainDashboardVendorsVendorIdRouteRoute
    }
    '/(main)/vendor/(guard)/collections/': {
      id: '/(main)/vendor/(guard)/collections/'
      path: '/collections'
      fullPath: '/vendor/collections/'
      preLoaderRoute: typeof mainVendorguardCollectionsIndexRouteImport
      parentRoute: typeof mainVendorguardRouteRoute
    }
    '/(main)/vendor/(guard)/deposits/': {
      id: '/(main)/vendor/(guard)/deposits/'
      path: '/deposits'
      fullPath: '/vendor/deposits/'
      preLoaderRoute: typeof mainVendorguardDepositsIndexRouteImport
      parentRoute: typeof mainVendorguardRouteRoute
    }
    '/(main)/vendor/(guard)/payouts/': {
      id: '/(main)/vendor/(guard)/payouts/'
      path: '/payouts'
      fullPath: '/vendor/payouts/'
      preLoaderRoute: typeof mainVendorguardPayoutsIndexRouteImport
      parentRoute: typeof mainVendorguardRouteRoute
    }
    '/(main)/vendor/(guard)/profile/': {
      id: '/(main)/vendor/(guard)/profile/'
      path: '/profile'
      fullPath: '/vendor/profile/'
      preLoaderRoute: typeof mainVendorguardProfileIndexRouteImport
      parentRoute: typeof mainVendorguardRouteRoute
    }
    '/(main)/vendor/(guard)/route/': {
      id: '/(main)/vendor/(guard)/route/'
      path: '/route'
      fullPath: '/vendor/route/'
      preLoaderRoute: typeof mainVendorguardRouteIndexRouteImport
      parentRoute: typeof mainVendorguardRouteRoute
    }
    '/(main)/vendor/(guard)/support/': {
      id: '/(main)/vendor/(guard)/support/'
      path: '/support'
      fullPath: '/vendor/support/'
      preLoaderRoute: typeof mainVendorguardSupportIndexRouteImport
      parentRoute: typeof mainVendorguardRouteRoute
    }
    '/(main)/dashboard/vendors/$vendorId/access/': {
      id: '/(main)/dashboard/vendors/$vendorId/access/'
      path: '/access'
      fullPath: '/dashboard/vendors/$vendorId/access/'
      preLoaderRoute: typeof mainDashboardVendorsVendorIdAccessIndexRouteImport
      parentRoute: typeof mainDashboardVendorsVendorIdRouteRoute
    }
    '/(main)/dashboard/vendors/$vendorId/preview/': {
      id: '/(main)/dashboard/vendors/$vendorId/preview/'
      path: '/preview'
      fullPath: '/dashboard/vendors/$vendorId/preview/'
      preLoaderRoute: typeof mainDashboardVendorsVendorIdPreviewIndexRouteImport
      parentRoute: typeof mainDashboardVendorsVendorIdRouteRoute
    }
    '/(main)/vendor/(guard)/stops/$stopId/': {
      id: '/(main)/vendor/(guard)/stops/$stopId/'
      path: '/stops/$stopId'
      fullPath: '/vendor/stops/$stopId/'
      preLoaderRoute: typeof mainVendorguardStopsStopIdIndexRouteImport
      parentRoute: typeof mainVendorguardRouteRoute
    }
  }
}

interface mainDashboardOrdersRouteRouteChildren {
  mainDashboardOrdersOrderIdRouteRoute: typeof mainDashboardOrdersOrderIdRouteRoute
  mainDashboardOrdersIndexRoute: typeof mainDashboardOrdersIndexRoute
}

const mainDashboardOrdersRouteRouteChildren: mainDashboardOrdersRouteRouteChildren =
  {
    mainDashboardOrdersOrderIdRouteRoute: mainDashboardOrdersOrderIdRouteRoute,
    mainDashboardOrdersIndexRoute: mainDashboardOrdersIndexRoute,
  }

const mainDashboardOrdersRouteRouteWithChildren =
  mainDashboardOrdersRouteRoute._addFileChildren(
    mainDashboardOrdersRouteRouteChildren,
  )

interface mainDashboardUsersRouteRouteChildren {
  mainDashboardUsersUserIdRouteRoute: typeof mainDashboardUsersUserIdRouteRoute
  mainDashboardUsersIndexRoute: typeof mainDashboardUsersIndexRoute
}

const mainDashboardUsersRouteRouteChildren: mainDashboardUsersRouteRouteChildren =
  {
    mainDashboardUsersUserIdRouteRoute: mainDashboardUsersUserIdRouteRoute,
    mainDashboardUsersIndexRoute: mainDashboardUsersIndexRoute,
  }

const mainDashboardUsersRouteRouteWithChildren =
  mainDashboardUsersRouteRoute._addFileChildren(
    mainDashboardUsersRouteRouteChildren,
  )

interface mainDashboardVendorsVendorIdRouteRouteChildren {
  mainDashboardVendorsVendorIdIndexRoute: typeof mainDashboardVendorsVendorIdIndexRoute
  mainDashboardVendorsVendorIdAccessIndexRoute: typeof mainDashboardVendorsVendorIdAccessIndexRoute
  mainDashboardVendorsVendorIdPreviewIndexRoute: typeof mainDashboardVendorsVendorIdPreviewIndexRoute
}

const mainDashboardVendorsVendorIdRouteRouteChildren: mainDashboardVendorsVendorIdRouteRouteChildren =
  {
    mainDashboardVendorsVendorIdIndexRoute:
      mainDashboardVendorsVendorIdIndexRoute,
    mainDashboardVendorsVendorIdAccessIndexRoute:
      mainDashboardVendorsVendorIdAccessIndexRoute,
    mainDashboardVendorsVendorIdPreviewIndexRoute:
      mainDashboardVendorsVendorIdPreviewIndexRoute,
  }

const mainDashboardVendorsVendorIdRouteRouteWithChildren =
  mainDashboardVendorsVendorIdRouteRoute._addFileChildren(
    mainDashboardVendorsVendorIdRouteRouteChildren,
  )

interface mainDashboardVendorsRouteRouteChildren {
  mainDashboardVendorsVendorIdRouteRoute: typeof mainDashboardVendorsVendorIdRouteRouteWithChildren
  mainDashboardVendorsIndexRoute: typeof mainDashboardVendorsIndexRoute
}

const mainDashboardVendorsRouteRouteChildren: mainDashboardVendorsRouteRouteChildren =
  {
    mainDashboardVendorsVendorIdRouteRoute:
      mainDashboardVendorsVendorIdRouteRouteWithChildren,
    mainDashboardVendorsIndexRoute: mainDashboardVendorsIndexRoute,
  }

const mainDashboardVendorsRouteRouteWithChildren =
  mainDashboardVendorsRouteRoute._addFileChildren(
    mainDashboardVendorsRouteRouteChildren,
  )

interface mainDashboardRouteRouteChildren {
  mainDashboardAuditRouteRoute: typeof mainDashboardAuditRouteRoute
  mainDashboardConfigRouteRoute: typeof mainDashboardConfigRouteRoute
  mainDashboardDefaultRouteRoute: typeof mainDashboardDefaultRouteRoute
  mainDashboardLedgerRouteRoute: typeof mainDashboardLedgerRouteRoute
  mainDashboardOrdersRouteRoute: typeof mainDashboardOrdersRouteRouteWithChildren
  mainDashboardPaymentsRouteRoute: typeof mainDashboardPaymentsRouteRoute
  mainDashboardTrustRouteRoute: typeof mainDashboardTrustRouteRoute
  mainDashboardUsersRouteRoute: typeof mainDashboardUsersRouteRouteWithChildren
  mainDashboardVendorsRouteRoute: typeof mainDashboardVendorsRouteRouteWithChildren
  mainDashboardSplatRoute: typeof mainDashboardSplatRoute
  mainDashboardIndexRoute: typeof mainDashboardIndexRoute
  mainDashboardAnalyticsIndexRoute: typeof mainDashboardAnalyticsIndexRoute
  mainDashboardDispatchIndexRoute: typeof mainDashboardDispatchIndexRoute
  mainDashboardFinanceIndexRoute: typeof mainDashboardFinanceIndexRoute
}

const mainDashboardRouteRouteChildren: mainDashboardRouteRouteChildren = {
  mainDashboardAuditRouteRoute: mainDashboardAuditRouteRoute,
  mainDashboardConfigRouteRoute: mainDashboardConfigRouteRoute,
  mainDashboardDefaultRouteRoute: mainDashboardDefaultRouteRoute,
  mainDashboardLedgerRouteRoute: mainDashboardLedgerRouteRoute,
  mainDashboardOrdersRouteRoute: mainDashboardOrdersRouteRouteWithChildren,
  mainDashboardPaymentsRouteRoute: mainDashboardPaymentsRouteRoute,
  mainDashboardTrustRouteRoute: mainDashboardTrustRouteRoute,
  mainDashboardUsersRouteRoute: mainDashboardUsersRouteRouteWithChildren,
  mainDashboardVendorsRouteRoute: mainDashboardVendorsRouteRouteWithChildren,
  mainDashboardSplatRoute: mainDashboardSplatRoute,
  mainDashboardIndexRoute: mainDashboardIndexRoute,
  mainDashboardAnalyticsIndexRoute: mainDashboardAnalyticsIndexRoute,
  mainDashboardDispatchIndexRoute: mainDashboardDispatchIndexRoute,
  mainDashboardFinanceIndexRoute: mainDashboardFinanceIndexRoute,
}

const mainDashboardRouteRouteWithChildren =
  mainDashboardRouteRoute._addFileChildren(mainDashboardRouteRouteChildren)

interface mainVendorguardRouteRouteChildren {
  mainVendorguardIndexRoute: typeof mainVendorguardIndexRoute
  mainVendorguardCollectionsIndexRoute: typeof mainVendorguardCollectionsIndexRoute
  mainVendorguardDepositsIndexRoute: typeof mainVendorguardDepositsIndexRoute
  mainVendorguardPayoutsIndexRoute: typeof mainVendorguardPayoutsIndexRoute
  mainVendorguardProfileIndexRoute: typeof mainVendorguardProfileIndexRoute
  mainVendorguardRouteIndexRoute: typeof mainVendorguardRouteIndexRoute
  mainVendorguardSupportIndexRoute: typeof mainVendorguardSupportIndexRoute
  mainVendorguardStopsStopIdIndexRoute: typeof mainVendorguardStopsStopIdIndexRoute
}

const mainVendorguardRouteRouteChildren: mainVendorguardRouteRouteChildren = {
  mainVendorguardIndexRoute: mainVendorguardIndexRoute,
  mainVendorguardCollectionsIndexRoute: mainVendorguardCollectionsIndexRoute,
  mainVendorguardDepositsIndexRoute: mainVendorguardDepositsIndexRoute,
  mainVendorguardPayoutsIndexRoute: mainVendorguardPayoutsIndexRoute,
  mainVendorguardProfileIndexRoute: mainVendorguardProfileIndexRoute,
  mainVendorguardRouteIndexRoute: mainVendorguardRouteIndexRoute,
  mainVendorguardSupportIndexRoute: mainVendorguardSupportIndexRoute,
  mainVendorguardStopsStopIdIndexRoute: mainVendorguardStopsStopIdIndexRoute,
}

const mainVendorguardRouteRouteWithChildren =
  mainVendorguardRouteRoute._addFileChildren(mainVendorguardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  mainDashboardRouteRoute: mainDashboardRouteRouteWithChildren,
  externalIndexRoute: externalIndexRoute,
  mainVendorguardRouteRoute: mainVendorguardRouteRouteWithChildren,
  mainAuthV1LoginRouteRoute: mainAuthV1LoginRouteRoute,
  mainVendorLoginIndexRoute: mainVendorLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
